# Generated by Django 3.0.6 on 2020-05-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200526_1459'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='added_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Project_Member'),
        ),
    ]
