# Generated by Django 3.0.6 on 2020-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200528_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
