# Generated by Django 3.0.6 on 2020-05-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_todo_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='delete',
        ),
    ]
