# Generated by Django 3.0.6 on 2020-06-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_todo_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
