# Generated by Django 3.0.6 on 2020-07-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
