# Generated by Django 3.0.6 on 2020-07-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_notification'),
        ('forum', '0004_auto_20200705_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_creater', to='accounts.Project_Member'),
        ),
    ]
