# Generated by Django 3.0.6 on 2020-07-07 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_notification'),
        ('forum', '0006_auto_20200705_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_posted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_posted_by', to='accounts.Project_Member'),
        ),
    ]
