# Generated by Django 3.0.6 on 2020-07-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20200707_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.TextField(default=None, null=True),
        ),
    ]
