# Generated by Django 3.0.6 on 2020-07-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_notification'),
        ('forum', '0008_post_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='quote',
            new_name='quote_content',
        ),
        migrations.AddField(
            model_name='post',
            name='quote_sender',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_sender', to='accounts.Project_Member'),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_sender', to='accounts.Project_Member'),
        ),
    ]
