# Generated by Django 3.0.7 on 2020-07-15 10:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_project_last_modified_item'),
        ('forum', '0014_auto_20200714_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(default=None, null=True, related_name='forum_post', to='accounts.Project_Member'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='quote_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
    ]
