# Generated by Django 3.0.7 on 2020-07-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_project_last_modified_item'),
        ('forum', '0015_auto_20200715_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='forum_post', to='accounts.Project_Member'),
        ),
    ]
