# Generated by Django 3.0.6 on 2020-05-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200525_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_admin',
        ),
        migrations.DeleteModel(
            name='Project_Admin',
        ),
    ]
