# Generated by Django 3.0.6 on 2020-06-08 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_project_project_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_admin',
        ),
        migrations.AddField(
            model_name='project',
            name='project_admin',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
