# Generated by Django 3.0.6 on 2020-06-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200608_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='calendar_month',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
