# Generated by Django 3.0.7 on 2020-06-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200614_1017'),
        ('accounts', '0013_auto_20200614_2148'),
    ]

    operations = [
    ]
