# Generated by Django 3.0.6 on 2020-07-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200701_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
