# Generated by Django 3.0.6 on 2020-07-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='forum_last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='forum_last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_last_modified', to='accounts.Project_Member'),
        ),
    ]
