# Generated by Django 3.0.6 on 2020-06-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_event_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='todo',
        ),
    ]
