# Generated by Django 3.0.6 on 2020-06-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20200622_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
