# Generated by Django 3.0.6 on 2020-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_auto_20200622_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='label',
            field=models.CharField(blank=True, choices=[('Meeting', 'Meeting'), ('Submission', 'Submission'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
