# Generated by Django 3.0.6 on 2020-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_auto_20200623_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
