# Generated by Django 3.0.6 on 2020-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0014_auto_20200623_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
