# Generated by Django 3.0.6 on 2020-06-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0016_auto_20200623_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
