# Generated by Django 3.0.6 on 2020-07-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0020_auto_20200717_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
