# Generated by Django 3.0.6 on 2020-06-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_project_project_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=50, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Project_Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
            ],
        ),
    ]
