# Generated by Django 3.0.6 on 2020-06-07 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200607_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
