# Generated by Django 3.0.6 on 2020-06-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='added_by',
            new_name='last_modified_by',
        ),
    ]
