# Generated by Django 3.0.6 on 2020-06-22 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200614_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='rank',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
