# Generated by Django 3.0.6 on 2020-06-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200622_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='rank',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
