# Generated by Django 3.0.6 on 2020-06-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200622_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
