# Generated by Django 3.0.6 on 2020-07-01 06:11

import accounts.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20200616_1652'),
        ('todo', '0009_auto_20200623_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assigned_to',
            field=models.ForeignKey(default=accounts.models.Project_Member, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_assigned_to', to='accounts.Project_Member'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
