# Generated by Django 3.0.7 on 2020-07-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20200701_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline_year',
            field=models.IntegerField(null=True),
        ),
    ]
